basePath: /
definitions:
  entity.AnyAddress:
    properties:
      api:
        type: string
      bairro:
        type: string
      cep:
        type: string
      localidade:
        type: string
      logradouro:
        type: string
      uf:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: giovani.angelo@gmail.com
    name: Giovani Angelo
  description: Fullcycle Pós Go Expert Go Expert
  termsOfService: http://swagger.io/terms/
  title: Desafio 2.0 - Multithreading
  version: "1.0"
paths:
  /cep/{cep}:
    get:
      consumes:
        - application/json
      description: Get Address by Post Code
      parameters:
        - description: Cep
          in: path
          name: cep
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/entity.AnyAddress"
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get Address
      tags:
        - address
swagger: "2.0"
